### ISSUE TITLE
[mdoc][bug] StackOverflowException when running through the assemblies

### ISSUE THREAD

**Issue by dend** [mono/api-doc-tools#134]
When running latest `mdoc` (5.0.0.25) in frameworks mode over the UWP content, I am getting a `StackOverflowException`. There are no details given even with `--debug` in the command.

Binaries that can help repro the issue:
[content.zip](https://github.com/mono/api-doc-tools/files/1380964/content.zip)

**Comment by dend** [comment]
Digging through our older conversations with @joelmartinez, this could be previously caused by `public sealed class WeakEventListener&lt;TInstance,TSource,TEventArgs&gt; where TInstance : class` inside `Microsoft.Toolkit.Uwp, 2.0.0.0` that caused a recursive lock:

```
at Mono.Cecil.ExportedType.Resolve()
   at Mono.Cecil.MetadataResolver.GetType(ModuleDefinition module, TypeReference reference)
   at Mono.Cecil.MetadataResolver.Resolve(TypeReference type)
   at Mono.Cecil.ModuleDefinition.Resolve(TypeReference type)
   at Mono.Cecil.ExportedType.Resolve()
   at Mono.Cecil.MetadataResolver.GetType(ModuleDefinition module, TypeReference reference)
   at Mono.Cecil.MetadataResolver.Resolve(TypeReference type)
   at Mono.Cecil.ModuleDefinition.Resolve(TypeReference type)
   at Mono.Cecil.ExportedType.Resolve()
```

It is attempting to resolve `System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089`.

![image](https://user-images.githubusercontent.com/1389609/31523968-80b41fb6-af6b-11e7-9253-c3c0ad081204.png)

**Comment by joelmartinez** [comment]
Ahh, this is perfect, thanks @dend !! This will be resolved with my almost-completed work on the new assembly resolver.

**Comment by joelmartinez** [comment]
This error is still occurring, but now against a different set of assemblies than the originally reported ones ... @TianqiZheng, please see if you can give me access to the set of assemblies that is triggering this issue (can be via email/fileshare if necessary).

/fyi @dend

**Comment by dend** [comment]
Looks like this issue is back 😄 

```
2017-12-04T16:05:53.2512451Z Member Added: public static System.Collections.Generic.IReadOnlyList<R> ToList<T,R> (this System.Collections.Generic.IReadOnlyList<T> source, Func<T,R> selector);
2017-12-04T16:05:53.2512451Z Member Added: public static System.Collections.Generic.IEnumerable<int> Enumerate (this Microsoft.Bot.Builder.Internals.Fibers.Range<int> range);
2017-12-04T16:06:15.0810834Z ##[error]Process is terminated due to StackOverflowException.
```
I see this when running through Bot Framework assemblies, the same ones as here:
https://github.com/mono/api-doc-tools/issues/174#issuecomment-348742241

cc: @joelmartinez

**Comment by dend** [comment]
Same happens for Azure assemblies:

```
2017-12-04T16:26:13.3449284Z Updating: Microsoft.Azure.Documents.UserDefinedFunction
2017-12-04T16:26:13.4699231Z Updating: Microsoft.Azure.Documents.UserDefinedFunctionType
2017-12-04T16:26:13.6418192Z Updating: Microsoft.Azure.Documents.ReplicationPolicy
2017-12-04T16:26:13.9387283Z Updating: Microsoft.Azure.Documents.Partitioning.Range`1
2017-12-04T16:26:43.1955416Z ##[error]Process is terminated due to StackOverflowException.
```
