### ISSUE TITLE
mdoc 5.3.3 breaks in frameworks mode

### ISSUE THREAD

**Issue by dend** [mono/api-doc-tools#174]
When running the latest `mdoc` release in frameworks mode, it breaks with the following error:

```
2017-12-03T04:39:26.9611841Z ##[error]mdoc: System.ArgumentOutOfRangeException: Length cannot be less than zero.
Parameter name: length
   at System.String.Substring(Int32 startIndex, Int32 length)
   at Mono.Documentation.Util.AttachedEntitiesHelper.GetEventName(String fieldDefinitionName)
   at Mono.Documentation.Util.AttachedEntitiesHelper.IsAttachedEvent(FieldDefinition field, Dictionary`2 methods)
   at Mono.Documentation.Util.AttachedEntitiesHelper.<GetAttachedEvents>d__8.MoveNext()
   at Mono.Documentation.Util.AttachedEntitiesHelper.<GetAttachedEntities>d__6.MoveNext()
   at Mono.Documentation.Util.CecilExtensions.<GetMembers>d__1.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at Mono.Documentation.MDocUpdater.Run(IEnumerable`1 args)
   at Mono.Documentation.MDoc.Run(String[] args)
   at Mono.Documentation.MDoc.Main(String[] args)
See `mdoc help' for more information or use --debug to diagnose.
```

Looks like the length is being reduced to below zero [here](https://github.com/mono/api-doc-tools/blob/master/mdoc/Mono.Documentation/Util/AttachedEntitiesHelper.cs#L19).

**Comment by dend** [comment]
Debugging the app, I see that it breaks when trying to pull in information on `EndConversationEvent`.

Full event is identified as:

```
Microsoft.Bot.Builder.Dialogs.EndConversationEvent Microsoft.Bot.Builder.Dialogs.EndConversationEvent/<>c/<<MakeScorable>b__4_0>d::e
```

Here is what's seen as the name:
<img width="579" alt="screen shot 2017-12-02 at 9 37 09 pm" src="https://user-images.githubusercontent.com/1389609/33522758-fc94a5b4-d7a8-11e7-9589-c6ca0fc2efb7.png">

This will, of course, cause a length check to fail.

**Comment by dend** [comment]
Here is the set of DLLs that I am testing with:

[1795-artifacts.zip](https://github.com/mono/api-doc-tools/files/1524520/1795-artifacts.zip)

The convention to check whether something is an event is today represented by:

```
if (!field.FieldType.Name.EndsWith(EventConst))
                return false;
```

As it turns out, this won't always be reliable as it will sometimes catch things that are not events:

<img width="1680" alt="screen shot 2017-12-02 at 9 47 01 pm" src="https://user-images.githubusercontent.com/1389609/33522793-5d4f77ca-d7aa-11e7-84b4-43722b2f84b7.png">

**Comment by dend** [comment]
After more investigation, looks like we might want to check if the field is of type `RoutedEvent` to make sure we are actually dealing with an attached event rather than relying on just the name.

**Comment by joelmartinez** [comment]
@dend @mpMelnikov please note, I've re-opened this ... see comment here: https://github.com/mono/api-doc-tools/pull/175#issuecomment-348758340
