### ISSUE TITLE
[mdoc] CI job breaks for .NET assemblies

### ISSUE THREAD

**Issue by dend** [mono/api-doc-tools#188]
When running `mdoc` on existing .NET platform assemblies, the tool errors out with:

```
2017-12-14T19:06:51.4374595Z Framework configuration file written to D:\a\1\s\source_repo\dotnet\frameworks.xml
2017-12-14T19:06:51.6418588Z Opening frameworks file 'D:\a\1\s\source_repo\dotnet\frameworks.xml'
2017-12-14T19:06:51.7783602Z Frameworks Configuration contains 1824 assemblies
2017-12-14T19:06:57.5354394Z ##[error]mdoc: System.NotSupportedException: System.Windows.RoutedEvent System.Windows.DataObject::Copying
   at Mono.Cecil.Rocks.DocCommentId.GetDocCommentId(IMemberDefinition member)
   at Mono.Documentation.Updater.Frameworks.FrameworkTypeEntry.ProcessMember(MemberReference member)
   at Mono.Documentation.MDocUpdater.Run(IEnumerable`1 args)
   at Mono.Documentation.MDoc.Run(String[] args)
   at Mono.Documentation.MDoc.Main(String[] args)
See `mdoc help' for more information or use --debug to diagnose.
```

**Comment by joelmartinez** [comment]
This issue stems from the added types added for #63 ... `AttachedEventDefinition` and `AttachedEventReference`. These custom types are, as expected, not supported by `DocCommentId.GetDocCommentId` in mono.cecil. 

Instead of using that API directly, I'm going to switch it to use `DocIdFormatter`, which has support for these types baked in.
