### ISSUE TITLE
[mdoc] Fails when reflecting UWP assemblies

### ISSUE THREAD

**Issue by dend** [mono/api-doc-tools#214]
When reflecting UWP assemblies, `mdoc` fails with:

```
2018-03-12T06:04:35.6666650Z Member Added: public object Convert (object value, Type targetType, object parameter, string language);
2018-03-12T06:04:35.6666650Z Member Added: public object ConvertBack (object value, Type targetType, object parameter, string language);
2018-03-12T06:04:35.8250340Z ##[error]mdoc: System.NullReferenceException: Object reference not set to an instance of an object.
   at Mono.Documentation.MDocUpdater.CleanupFiles(String dest, HashSet`1 goodfiles)
   at Mono.Documentation.MDocUpdater.DoUpdateAssemblies(String source, String dest)
   at Mono.Documentation.MDocUpdater.Run(IEnumerable`1 args)
   at Mono.Documentation.MDoc.Run(String[] args)
   at Mono.Documentation.MDoc.Main(String[] args)
See `mdoc help' for more information or use --debug to diagnose.
```

[uwp-new.zip](https://github.com/mono/api-doc-tools/files/1801572/uwp-new.zip)

cc: @joelmartinez

**Comment by joelmartinez** [comment]
@dend ... do you know what version this occurred in? was it the 5.5.1 preview 5 release, or 5.5.0.1?

I ran these assemblies locally without error, so I'm trying to verify which version this occurred in.

**Comment by dend** [comment]
@joelmartinez this is the release I am using:
https://github.com/mono/api-doc-tools/releases/download/mdoc-5.5.1-preview5/mdoc-5.5.1-preview5.zip 

This is CLI runner:
& ($Env:BUILD_REPOSITORY_LOCALPATH + "\_bin\mdoc.exe") update -fx ($Env:BUILD_REPOSITORY_LOCALPATH + "\_all") -o  ($Env:BUILD_REPOSITORY_LOCALPATH + "\_all-out") --debug -lang docid -lang vb.net -lang fsharp -lang c++/cli -lang c++/cx -lang c++/winrt --delete -L "C:\Program Files (x86)\Windows Kits\10\References\10.0.15063.0"

Running over the content in:
https://github.com/MicrosoftDocs/UWPCommunityToolkitDocs/tree/master/dotnet/xml

**Comment by joelmartinez** [comment]
@dend, is this still an issue with the latest build(s) of mdoc?

**Comment by dend** [comment]
@joelmartinez does not seem to be teh case right now. This can be closed for now.
