### ISSUE TITLE
[mdoc][release 5.0.0.2] Cannot find file on reflecting multiple frameworks

### ISSUE THREAD

**Issue by dend** [mono/api-doc-tools#26]
I have the following set of assemblies to reflect from:

![capture](https://cloud.githubusercontent.com/assets/1389609/23136137/1f94fdfa-f750-11e6-8e8d-41a21cfb91e3.PNG)

I then get the following error, when I try to run `mdoc` with the `-frameworks` parameter that points to the source folder:
```
mdoc: System.IO.FileNotFoundException: Could not find file 'C:\Users\dendeli\Downloads\DLLs\netframework-2.0\System.EnterpriseServices.Wrapper.dll'.
File name: 'C:\Users\dendeli\Downloads\DLLs\netframework-2.0\System.EnterpriseServices.Wrapper.dll'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Mono.Cecil.ModuleDefinition.ReadModule(String fileName, ReaderParameters parameters)
   at Mono.Cecil.MetadataReader.ReadModules()
   at Mono.Cecil.AssemblyDefinition.<get_Modules>m__0(AssemblyDefinition _, MetadataReader reader)
   at Mono.Cecil.ModuleDefinition.Read[TItem,TRet](TRet& variable, TItem item, Func`3 read)
   at Mono.Cecil.AssemblyDefinition.get_Modules()
   at Mono.Documentation.CecilExtensions.GetTypes(AssemblyDefinition assembly)
   at Mono.Documentation.DocumentationEnumerator.<GetDocumentationTypes>c__Iterator0.MoveNext()
   at Mono.Documentation.MDocUpdater.DoUpdateAssembly(AssemblyDefinition assembly, XmlElement index_types, String source, String dest, HashSet`1 goodfiles)
   at Mono.Documentation.MDocUpdater.DoUpdateAssemblies(String source, String dest)
   at Mono.Documentation.MDocUpdater.Run(IEnumerable`1 args)
   at Mono.Documentation.MDoc.Run(String[] args)
   at Mono.Documentation.MDoc.Main(String[] args)
See `mdoc help' for more information or use --debug to diagnose.
```

**Comment by joelmartinez** [comment]
I was unable to reproduce this error, and with the change in 39d400cc3113c71becb36b0cb7be28a7c479b988 (coming in preview v5.0.0.3), you shouldn't encounter this. I'm going to close the bug ... though please re-open if you re-encounter the issue.

**Comment by dend** [comment]
@joelmartinez still happens. I have the following frameworks in a folder:

* .NET Framework 2.0
* .NET Framework 3.0
* .NET Framework 3.5
* .NET Framework 4.0

When I run `mdoc update -o OUTPUT_FOLDER --frameworks FOLDER_CONTAINER_OF_FRAMEWORKS`, it will run for a bit and then hit this error.

**Comment by joelmartinez** [comment]
ok, so with the test set I was able to reproduce this ... but in fact, `System.EnterpriseServices.Wrapper.dll` *is* missing from those folders. When I copied it from `.NET Framework 4.0` into the 2, 3, and 3.5 folders, it was able to complete.

As I mentioned in https://github.com/mono/api-doc-tools/issues/8#issuecomment-282410843 , it doesn't look like that's a managed assembly. But perhaps there's just something out of sorts here ...  I'm not sure why the metadata would be asking Mono.Cecil to load `.Wrapper.dll` if there wasn't a reference to it, and if so, why it wouldn't be included in those other version folders.

I have a _theory_, that this might have something to do with the fact that currently, mdoc is using the same `AssemblyResolver` for every loaded assembly. As I mentioned here, https://github.com/mono/api-doc-tools/pull/18#issuecomment-280845612 , I'm going to be changing the code to use one resolver for every framework, so one of two things will happen:

- The problem goes away entirely because it was just an artifact of mixing all frameworks together.
- The problem persists, and the solution is to include the required `.Wrapper.dll` file in the same folder.

I'm going to leave this item open until I can verify which one it is ... but in the meantime @dend, you can work around this error by copying.

**Comment by dend** [comment]
Thanks for investigating @joelmartinez. Want to also make sure that we are not including unnecessary assemblies in frameworks where those don't belong.

**Comment by dend** [comment]
Confirmed that the new release still has this issue in `-fx` mode.

**Comment by joelmartinez** [comment]
So I made a standalone project to verify/test this, and it's getting this error when trying to resolve this type:

`System.EnterpriseServices.Thunk.ServiceConfigThunk`

Having the file in a directory that you've added as a search directory isn't enough, it seems to need the `.Wrapper.dll` in the same directory as `System.EnterpriseServices.dll` to work. As I [mentioned here](https://github.com/mono/api-doc-tools/issues/8#issuecomment-282410843), it doesn't load ... so including it in the directory won't add any types to the XML (since Cecil can't read it by loading the assembly.  

Again, I'm not really sure what is the root cause here as I'm not super familiar with this library, but it doesn't seem like copying that file into the folder will cause any unwanted artifacts in the output.
