### ISSUE TITLE
[mdoc][release 5.0.0.2] Error when reflecting from XamlBuildTypeInspectionExtensionContext

### ISSUE THREAD

**Issue by dend** [mono/api-doc-tools#27]
Getting the following error:

```
Updating: Microsoft.Build.Tasks.Xaml.XamlBuildTypeGenerationExtensionContext
Updating: Microsoft.Build.Tasks.Xaml.XamlBuildTypeInspectionExtensionContext
mdoc: System.InvalidOperationException: Failed to compare two elements in the array. ---> System.InvalidOperationException: Duplicate extension method found!
   at Mono.Documentation.MDocUpdater.ExtensionMethodComparer.Compare(XmlNode x, XmlNode y)
   at System.Collections.Generic.ArraySortHelper`1.PickPivotAndPartition(T[] keys, Int32 lo, Int32 hi, IComparer`1 comparer)
   at System.Collections.Generic.ArraySortHelper`1.IntroSort(T[] keys, Int32 lo, Int32 hi, Int32 depthLimit, IComparer`1 comparer)
   at System.Collections.Generic.ArraySortHelper`1.IntrospectiveSort(T[] keys, Int32 left, Int32 length, IComparer`1 comparer)
   at System.Collections.Generic.ArraySortHelper`1.Sort(T[] keys, Int32 index, Int32 length, IComparer`1 comparer)
   --- End of inner exception stack trace ---
   at System.Collections.Generic.ArraySortHelper`1.Sort(T[] keys, Int32 index, Int32 length, IComparer`1 comparer)
   at System.Array.Sort[T](T[] array, Int32 index, Int32 length, IComparer`1 comparer)
   at System.Collections.Generic.List`1.Sort(Int32 index, Int32 count, IComparer`1 comparer)
   at Mono.Documentation.MDocUpdater.CleanupExtensions(XmlElement index_types)
   at Mono.Documentation.MDocUpdater.DoUpdateAssemblies(String source, String dest)
   at Mono.Documentation.MDocUpdater.Run(IEnumerable`1 args)
   at Mono.Documentation.MDoc.Run(String[] args)
   at Mono.Documentation.MDoc.Main(String[] args)
See `mdoc help' for more information or use --debug to diagnose.
```

This is caused by [Microsoft.Build.Tasks.Xaml.XamlBuildTypeGenerationExtensionContext](https://msdn.microsoft.com/en-us/library/microsoft.build.tasks.xaml.xamlbuildtypegenerationextensioncontext(v=vs.110).aspx), part of `XamlBuildTask.dll`.

**Comment by dend** [comment]
Also:

```
Updating: System.Windows.Automation.Peers.WindowsFormsHostAutomationPeer
mdoc: System.InvalidOperationException: Failed to compare two elements in the array. ---> System.InvalidOperationException: Duplicate extension method found!
   at Mono.Documentation.MDocUpdater.ExtensionMethodComparer.Compare(XmlNode x, XmlNode y)
   at System.Collections.Generic.ArraySortHelper`1.PickPivotAndPartition(T[] keys, Int32 lo, Int32 hi, IComparer`1 comparer)
   at System.Collections.Generic.ArraySortHelper`1.IntroSort(T[] keys, Int32 lo, Int32 hi, Int32 depthLimit, IComparer`1 comparer)
   at System.Collections.Generic.ArraySortHelper`1.IntrospectiveSort(T[] keys, Int32 left, Int32 length, IComparer`1 comparer)
   at System.Collections.Generic.ArraySortHelper`1.Sort(T[] keys, Int32 index, Int32 length, IComparer`1 comparer)
   --- End of inner exception stack trace ---
   at System.Collections.Generic.ArraySortHelper`1.Sort(T[] keys, Int32 index, Int32 length, IComparer`1 comparer)
   at System.Array.Sort[T](T[] array, Int32 index, Int32 length, IComparer`1 comparer)
   at System.Collections.Generic.List`1.Sort(Int32 index, Int32 count, IComparer`1 comparer)
   at Mono.Documentation.MDocUpdater.CleanupExtensions(XmlElement index_types)
   at Mono.Documentation.MDocUpdater.DoUpdateAssemblies(String source, String dest)
   at Mono.Documentation.MDocUpdater.Run(IEnumerable`1 args)
   at Mono.Documentation.MDoc.Run(String[] args)
   at Mono.Documentation.MDoc.Main(String[] args)
See `mdoc help' for more information or use --debug to diagnose.
```

This is associated with [System.Windows.Automation.Peers.WindowsFormsHostAutomationPeer](https://msdn.microsoft.com/en-us/library/system.windows.automation.peers.windowsformshostautomationpeer.aspx) in `WindowsFormsIntegration.dll`.

**Comment by dend** [comment]
One more:

```
Updating: System.Security.Permissions.MediaPermissionAttribute
mdoc: System.InvalidOperationException: Failed to compare two elements in the array. ---> System.InvalidOperationException: Duplicate extension method found!
   at Mono.Documentation.MDocUpdater.ExtensionMethodComparer.Compare(XmlNode x, XmlNode y)
   at System.Collections.Generic.ArraySortHelper`1.PickPivotAndPartition(T[] keys, Int32 lo, Int32 hi, IComparer`1 comparer)
   at System.Collections.Generic.ArraySortHelper`1.IntroSort(T[] keys, Int32 lo, Int32 hi, Int32 depthLimit, IComparer`1 comparer)
   at System.Collections.Generic.ArraySortHelper`1.IntrospectiveSort(T[] keys, Int32 left, Int32 length, IComparer`1 comparer)
   at System.Collections.Generic.ArraySortHelper`1.Sort(T[] keys, Int32 index, Int32 length, IComparer`1 comparer)
   --- End of inner exception stack trace ---
   at System.Collections.Generic.ArraySortHelper`1.Sort(T[] keys, Int32 index, Int32 length, IComparer`1 comparer)
   at System.Array.Sort[T](T[] array, Int32 index, Int32 length, IComparer`1 comparer)
   at System.Collections.Generic.List`1.Sort(Int32 index, Int32 count, IComparer`1 comparer)
   at Mono.Documentation.MDocUpdater.CleanupExtensions(XmlElement index_types)
   at Mono.Documentation.MDocUpdater.DoUpdateAssemblies(String source, String dest)
   at Mono.Documentation.MDocUpdater.Run(IEnumerable`1 args)
   at Mono.Documentation.MDoc.Run(String[] args)
   at Mono.Documentation.MDoc.Main(String[] args)
See `mdoc help' for more information or use --debug to diagnose.
```

Caused by [MediaPermissionAttribute](https://msdn.microsoft.com/en-us/library/system.security.permissions.mediapermissionattribute(v=vs.110).aspx) in WindowsBase.dll.

**Comment by dend** [comment]
Same error, for [System.Windows.Automation.Text.TextDecorationLineStyle](https://msdn.microsoft.com/en-us/library/system.windows.automation.text.textdecorationlinestyle(v=vs.110).aspx) in `UIAutomationTypes.dll`

**Comment by dend** [comment]
And the same for [System.Windows.Automation.Provider.IItemContainerProvider](https://msdn.microsoft.com/en-us/library/system.windows.automation.provider.iitemcontainerprovider(v=vs.110).aspx) in `UIAutomationProvider.dll`

**Comment by joelmartinez** [comment]
@dend can you give me a bit of context here ... are you running these with `-frameworks`, or just as a regular `mdoc update` and passing in various assemblies?

**Comment by dend** [comment]
@joelmartinez this is in `--frameworks` mode, with 7 different framework versions in the query.

**Comment by joelmartinez** [comment]
This issue is resolved, and will be merged to master in this PR:  
https://github.com/mono/api-doc-tools/pull/18
