### ISSUE TITLE
[mdoc][feature-request] Ability to reflect from *.winmd files

### ISSUE THREAD

**Issue by dend** [mono/api-doc-tools#29]
Currently, if I change the extension of a `*.winmd` file to `*.dll`, I will get this error:

```
mdoc: System.NotSupportedException: Version not supported: 255.255.255.255
   at Mono.Cecil.BaseAssemblyResolver.GetCorlib(AssemblyNameReference reference, ReaderParameters parameters)
   at Mono.Cecil.BaseAssemblyResolver.Resolve(AssemblyNameReference name, ReaderParameters parameters)
   at Mono.Cecil.DefaultAssemblyResolver.Resolve(AssemblyNameReference name)
   at Mono.Cecil.MetadataResolver.Resolve(TypeReference type)
   at Mono.Cecil.TypeReference.Resolve()
   at Mono.Documentation.DocUtils.GetInheritedInterfaces(TypeDefinition type)
   at Mono.Documentation.DocUtils.GetUserImplementedInterfaces(TypeDefinition type)
   at Mono.Documentation.CSharpFullMemberFormatter.GetTypeDeclaration(TypeDefinition type)
   at Mono.Documentation.MemberFormatter.GetDeclaration(IMemberDefinition member)
   at Mono.Documentation.MemberFormatter.GetDeclaration(MemberReference mreference)
   at Mono.Documentation.MDocUpdater.StubType(TypeDefinition type, String output)
   at Mono.Documentation.MDocUpdater.DoUpdateType(TypeDefinition type, FrameworkTypeEntry typeEntry, String basepath, String dest)
   at Mono.Documentation.MDocUpdater.DoUpdateAssembly(AssemblyDefinition assembly, XmlElement index_types, String source, String dest, HashSet`1 goodfiles)
   at Mono.Documentation.MDocUpdater.DoUpdateAssemblies(String source, String dest)
   at Mono.Documentation.MDocUpdater.Run(IEnumerable`1 args)
   at Mono.Documentation.MDoc.Run(String[] args)
   at Mono.Documentation.MDoc.Main(String[] args)
See `mdoc help' for more information or use --debug to diagnose.
```

`*.winmd` is an [ECMA 335 assembly](https://www.ecma-international.org/publications/standards/Ecma-335.htm) so should work the same way as any other managed DLL.

**Comment by joelmartinez** [comment]
@dend Should this target the 5.0 milestone?

**Comment by dend** [comment]
@joelmartinez no, not at all. Future request.

**Comment by dotMorten** [comment]
Can we add C++/CLI .NET assemblies to this list?

**Comment by joelmartinez** [comment]
Given that mono.cecil supports *.winmd, I'm guessing this will be the same solution as #58, just a matter of telling mdoc that it should process *.winmd files ... it is probably just getting confused since you changed the extension to .dll.

@dotMorten ... doesn't that still produce a *.dll, with .net metadata? or, to put it another way ... do we know that this doesn't work already?

**Comment by dend** [comment]
This seems to still be the case.
