### ISSUE TITLE
[mdoc] Tool breaks when hitting System.Printing.IndexedProperties.PrintDateTimeProperty

### ISSUE THREAD

**Issue by dend** [mono/api-doc-tools#33]
Getting the following error:

```
mdoc: System.InvalidCastException: Unable to cast object of type 'Mono.Cecil.OptionalModifierType' to type 'Mono.Cecil.RequiredModifierType'.
   at Mono.Cecil.Rocks.DocCommentId.WriteTypeSignature(TypeReference type)
   at Mono.Cecil.Rocks.DocCommentId.WriteReturnType(MethodDefinition method)
   at Mono.Cecil.Rocks.DocCommentId.WriteMethod(MethodDefinition method)
   at Mono.Cecil.Rocks.DocCommentId.GetDocCommentId(IMemberDefinition member)
   at Mono.Documentation.FrameworkTypeEntry.ProcessMember(MemberReference member)
   at Mono.Documentation.MDocUpdater.UpdateMember(DocsNodeInfo info, FrameworkTypeEntry typeEntry)
   at Mono.Documentation.MDocUpdater.MakeMember(XmlDocument doc, DocsNodeInfo info, FrameworkTypeEntry typeEntry)
   at Mono.Documentation.MDocUpdater.DoUpdateType2(String message, XmlDocument basefile, TypeDefinition type, FrameworkTypeEntry typeEntry, String output, Boolean insertSince)
   at Mono.Documentation.MDocUpdater.StubType(TypeDefinition type, String output)
   at Mono.Documentation.MDocUpdater.DoUpdateType(TypeDefinition type, FrameworkTypeEntry typeEntry, String basepath, String dest)
   at Mono.Documentation.MDocUpdater.DoUpdateAssembly(AssemblySet assemblySet, AssemblyDefinition assembly, XmlElement index_types, String source, String dest, HashSet`1 goodfiles)
   at Mono.Documentation.MDocUpdater.DoUpdateAssemblies(String source, String dest)
   at Mono.Documentation.MDocUpdater.Run(IEnumerable`1 args)
   at Mono.Documentation.MDoc.Run(String[] args)
   at Mono.Documentation.MDoc.Main(String[] args)
See `mdoc help' for more information or use --debug to diagnose.
```

Related to:
```
New Type: System.Printing.IndexedProperties.PrintDateTimeProperty
Member Added: public PrintDateTimeProperty (string attributeName, object attributeValue);
Member Added: public PrintDateTimeProperty (string attributeName);
```

In `System.Printing.dll`.

**Comment by joelmartinez** [comment]
In particular, this is coming from the following method ... an operator:

`System.ValueType modopt(System.DateTime) modopt(System.Runtime.CompilerServices.IsBoxed) System.Printing.IndexedProperties.PrintDateTimeProperty::op_Implicit(System.Printing.IndexedProperties.PrintDateTimeProperty)`

It seems to stem from an invalid cast [here](https://github.com/jbevain/cecil/blob/505b07d6974d8405a63124139733c6fdc0e67bc7/rocks/Mono.Cecil.Rocks/DocCommentId.cs#L114) in mono.cecil:

```csharp
				case MetadataType.OptionalModifier:
					WriteModiferTypeSignature ((RequiredModifierType) type, '!');
					break;
				case MetadataType.RequiredModifier:
					WriteModiferTypeSignature ((RequiredModifierType) type, '|');
					break;
```
The return type's `MetadataType` is `OptionalModifier` ... and in the code above, it's trying to cast it to `RequiredModifierType`.
