### ISSUE TITLE
mdoc fails with Unable to cast object of type 'Mono.Cecil.CustomAttributeArgument[]' to type 'System.IConvertible'

### ISSUE THREAD

**Issue by dend** [mono/api-doc-tools#340]
* [Libraries](https://apidrop.visualstudio.com/_git/binaries?path=%2Fbiztalk-rosetta-dotnet%2Fbts-rosettanet-accelerator&version=GBmaster)
* [Repo/Docset](https://github.com/MicrosoftDocs/biztalk-reference/tree/master/bts-rosettanet-accelerator)
* [CI Job](https://apidrop.visualstudio.com/Content%20CI/_build?definitionId=1202)

Error ([see build report](https://apidrop.visualstudio.com/Content%20CI/_build/results?buildId=28473&_a=summary&view=logs)):
```
mdoc: System.InvalidCastException: Unable to cast object of type 'Mono.Cecil.CustomAttributeArgument[]' to type 'System.IConvertible'.
at System.Convert.ToInt64(Object value)
at Mono.Documentation.Updater.AttributeValueFormatter.TryFormatValue(Object v, ResolvedTypeInfo type, String& returnvalue)
at Mono.Documentation.MDocUpdater.MakeAttributesValueString(Object v, TypeReference valueType)
at Mono.Documentation.MDocUpdater.<GetCustomAttributes>d__126.MoveNext()
at System.Linq.Enumerable.<ConcatIterator>d__59`1.MoveNext()
at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
at System.Linq.Enumerable.<DistinctIterator>d__64`1.MoveNext()
at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
at Mono.Documentation.MDocUpdater.MakeAttributes(XmlElement root, IEnumerable`1 attributes, FrameworkEntry fx)
at Mono.Documentation.MDocUpdater.UpdateType(XmlElement root, TypeDefinition type, FrameworkTypeEntry typeEntry)
at Mono.Documentation.MDocUpdater.DoUpdateType2(String message, XmlDocument basefile, TypeDefinition type, FrameworkTypeEntry typeEntry, String output, Boolean insertSince)
at Mono.Documentation.MDocUpdater.StubType(AssemblySet set, TypeDefinition type, String output, IEnumerable`1 importers, String Id, String Version)
at Mono.Documentation.MDocUpdater.DoUpdateType(AssemblySet set, TypeDefinition type, FrameworkTypeEntry typeEntry, String basepath, String dest)
at Mono.Documentation.MDocUpdater.DoUpdateAssembly(AssemblySet assemblySet, AssemblyDefinition assembly, XmlElement index_types, String source, String dest, HashSet`1 goodfiles)
at Mono.Documentation.MDocUpdater.DoUpdateAssemblies(String source, String dest)
at Mono.Documentation.MDocUpdater.Run(IEnumerable`1 args)
at Mono.Documentation.MDoc.Main(String[] args)
See `mdoc help' for more information or use --debug to diagnose.
2 more errors. Click on expand view in context menu to view complete logs.
```

**Comment by joelmartinez** [comment]
@dend Trying to reproduce this locally, but getting the error:

```
Failed to resolve assembly: 'Microsoft.XLANGs.BizTalk.ProcessInterface, Version=3.0.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
```

Seems like there's a missing assembly int he dependencies folder?
