### ISSUE TITLE
[mdoc] OutOfMemoryException when running against many frameworks

### ISSUE THREAD

**Issue by dend** [mono/api-doc-tools#49]
I am running `mdoc` against several frameworks, and while the process kicks off OK, somewhere mid-process (after 10+ minutes or running) the app crashes with an `OutOfMemoryException`:

```
mdoc: System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.String.InternalSubString(Int32 startIndex, Int32 length)
   at System.String.Substring(Int32 startIndex, Int32 length)
   at System.IO.Path.GetFileName(String path)
   at Mono.Documentation.AssemblySet.<Contains>c__AnonStorey2.<>m__0(String p)
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at Mono.Documentation.AssemblySet.Contains(String name)
   at Mono.Documentation.MDocUpdater.<IsInAssemblies>c__AnonStorey6.<>m__0(AssemblySet a)
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at Mono.Documentation.MDocUpdater.IsInAssemblies(String name)
   at Mono.Documentation.DocUtils.GetNamespace(TypeReference type)
   at Mono.Documentation.MemberFormatter.AppendNamespace(StringBuilder buf, TypeReference type)
   at Mono.Documentation.MemberFormatter._AppendTypeName(StringBuilder buf, TypeReference type, DynamicParserContext context)
   at Mono.Documentation.MemberFormatter.GetTypeName(TypeReference type, DynamicParserContext context)
   at Mono.Documentation.MemberFormatter.GetName(MemberReference member, DynamicParserContext context)
   at Mono.Documentation.MDocUpdater.<GetCustomAttributes>c__Iterator0.MoveNext()
   at System.Linq.Enumerable.<ConcatIterator>d__58`1.MoveNext()
   at System.Linq.Enumerable.<ConcatIterator>d__58`1.MoveNext()
   at System.Linq.Enumerable.<ConcatIterator>d__58`1.MoveNext()
   at Mono.Documentation.MDocUpdater.MakeAttributes(XmlElement root, IEnumerable`1 attributes, TypeReference t)
   at Mono.Documentation.MDocUpdater.UpdateMember(DocsNodeInfo info, FrameworkTypeEntry typeEntry)
   at Mono.Documentation.MDocUpdater.DoUpdateType2(String message, XmlDocument basefile, TypeDefinition type, FrameworkTypeEntry typeEntry, String output, Boolean insertSince)
   at Mono.Documentation.MDocUpdater.DoUpdateType(TypeDefinition type, FrameworkTypeEntry typeEntry, String basepath, String dest)
   at Mono.Documentation.MDocUpdater.DoUpdateAssembly(AssemblySet assemblySet, AssemblyDefinition assembly, XmlElement index_types, String source, String dest, HashSet`1 goodfiles)
   at Mono.Documentation.MDocUpdater.DoUpdateAssemblies(String source, String dest)
   at Mono.Documentation.MDocUpdater.Run(IEnumerable`1 args)
   at Mono.Documentation.MDoc.Run(String[] args)
   at Mono.Documentation.MDoc.Main(String[] args)
See `mdoc help' for more information or use --debug to diagnose.
```

My hunch is somewhere in the code there is a `List<T>` that takes more than 2GB in-memory space. Because `mdoc` is compiled as a x86 app, that limitation is by design, but we could probably do better.

As a workaround, it is possible to use `editbin` and run it on the `mdoc.exe` binary with the `/LARGEADDRESSAWARE` flag and get a binary that works without the exception.

The proposed fix is to compile `mdoc` as an `amd64` application.

**Comment by jonpryor** [comment]
Why not compile as an AnyCPU application?

**Comment by joelmartinez** [comment]
@jonpryor yep, that's what I was going to do :)
