### ISSUE TITLE
[mdoc] Error updating a generic extension method

### ISSUE THREAD

**Issue by joelmartinez** [mono/api-doc-tools#6]
If you've got an assembly with an extension method that looks like this

```csharp
    public static class ArrayX10 {
        public static bool IsAligned<T> (this T[] vect, int index) where T : struct 
        {
            return false;
        }
    }
```
You will receive the following error with `mdoc update`
```bash
mdoc: System.ArgumentNullException: Value cannot be null.
Parameter name: member
  at Mono.Documentation.MemberFormatter.GetDeclaration (Mono.Cecil.IMemberDefinition member) [0x00006] in <bdba0d7bb95b4ee498bb485f1da6983a>:0 
  at Mono.Documentation.MemberFormatter.GetDeclaration (Mono.Cecil.MemberReference mreference) [0x00007] in <bdba0d7bb95b4ee498bb485f1da6983a>:0 
  at Mono.Documentation.MDocUpdater.AddTargets (System.Xml.XmlNode member, Mono.Documentation.DocsNodeInfo info) [0x00055] in <bdba0d7bb95b4ee498bb485f1da6983a>:0 
  at Mono.Documentation.MDocUpdater.UpdateExtensionMethods (System.Xml.XmlElement e, Mono.Documentation.DocsNodeInfo info) [0x000d8] in <bdba0d7bb95b4ee498bb485f1da6983a>:0 
  at Mono.Documentation.MDocUpdater.UpdateMember (Mono.Documentation.DocsNodeInfo info) [0x0024b] in <bdba0d7bb95b4ee498bb485f1da6983a>:0 
  at Mono.Documentation.MDocUpdater.MakeMember (System.Xml.XmlDocument doc, Mono.Documentation.DocsNodeInfo info) [0x000c1] in <bdba0d7bb95b4ee498bb485f1da6983a>:0 
  at Mono.Documentation.MDocUpdater.DoUpdateType2 (System.String message, System.Xml.XmlDocument basefile, Mono.Cecil.TypeDefinition type, System.String output, System.Boolean insertSince) [0x00376] in <bdba0d7bb95b4ee498bb485f1da6983a>:0 
  at Mono.Documentation.MDocUpdater.StubType (Mono.Cecil.TypeDefinition type, System.String output) [0x00030] in <bdba0d7bb95b4ee498bb485f1da6983a>:0 
  at Mono.Documentation.MDocUpdater.DoUpdateType (Mono.Cecil.TypeDefinition type, System.String basepath, System.String dest) [0x001d9] in <bdba0d7bb95b4ee498bb485f1da6983a>:0 
  at Mono.Documentation.MDocUpdater.DoUpdateAssembly (Mono.Cecil.AssemblyDefinition assembly, System.Xml.XmlElement index_types, System.String source, System.String dest, System.Collections.Generic.HashSet`1[T] goodfiles) [0x0005d] in <bdba0d7bb95b4ee498bb485f1da6983a>:0 
  at Mono.Documentation.MDocUpdater.DoUpdateAssemblies (System.String source, System.String dest) [0x00125] in <bdba0d7bb95b4ee498bb485f1da6983a>:0 
  at Mono.Documentation.MDocUpdater.Run (System.Collections.Generic.IEnumerable`1[T] args) [0x00404] in <bdba0d7bb95b4ee498bb485f1da6983a>:0 
  at Mono.Documentation.MDoc.Run (System.String[] args) [0x001f6] in <bdba0d7bb95b4ee498bb485f1da6983a>:0 
  at Mono.Documentation.MDoc.Main (System.String[] args) [0x00006] in <bdba0d7bb95b4ee498bb485f1da6983a>:0 
See `mdoc help' for more information or use --debug to diagnose.
```

**Comment by joelmartinez** [comment]
@jonpryor given that `this` is a generic parameter ... what should the extension `Target` be?

```xml
      <Targets>
        <Target Type="T:T[]" />
      </Targets>
```

?

**Comment by jonpryor** [comment]
Uh...good question.

The intent of `//Targets/Target/@Type` is to be a CREF "selector" for straightforward querying within `monodoc.dll`, e.g. "I know the current type's CREF, e.g. `T:System.Collections.Generic.IEnumerable`1`, so I can query all loaded modules for extension methods which target that same CREF."

Here, though, we can target *everything*.

In any event...

What should the value be? [Whatever makes implementing extension method querying easier in `monodoc.dll`](https://github.com/mono/api-doc-tools/blob/34ddfb9/monodoc/Mono.Documentation/XmlDocUtils.cs#L115). ;-)

Based on `GetSupportedTypes()`, I think building atop `System.Object[]` might work, because `System.Object` value is always returned by `GetSupportedTypes()`.

The problem in this case is we're not doing an extension method on `T` (*anything*), but on `T[]`, and in C# an `int[]` isn't a `System.Object[]`, so having `<Target Type="T:System.Object[]" />` doesn't *quite* seem correct.

However, it might be good enough...

**Comment by dend** [comment]
@joelmartinez still getting this:

```
New Type: System.Windows.Threading.TaskExtensions
mdoc: System.ArgumentNullException: Value cannot be null.
Parameter name: member
   at Mono.Documentation.MemberFormatter.GetDeclaration(IMemberDefinition member)
   at Mono.Documentation.MemberFormatter.GetDeclaration(MemberReference mreference)
   at Mono.Documentation.MDocUpdater.AddTargets(XmlNode member, DocsNodeInfo info)
   at Mono.Documentation.MDocUpdater.UpdateExtensionMethods(XmlElement e, DocsNodeInfo info)
   at Mono.Documentation.MDocUpdater.UpdateMember(DocsNodeInfo info, FrameworkTypeEntry typeEntry)
   at Mono.Documentation.MDocUpdater.MakeMember(XmlDocument doc, DocsNodeInfo info, FrameworkTypeEntry typeEntry)
   at Mono.Documentation.MDocUpdater.DoUpdateType2(String message, XmlDocument basefile, TypeDefinition type, FrameworkTypeEntry typeEntry, String output, Boolean insertSince)
   at Mono.Documentation.MDocUpdater.StubType(TypeDefinition type, String output)
   at Mono.Documentation.MDocUpdater.DoUpdateType(TypeDefinition type, FrameworkTypeEntry typeEntry, String basepath, String dest)
   at Mono.Documentation.MDocUpdater.DoUpdateAssembly(AssemblyDefinition assembly, XmlElement index_types, String source, String dest, HashSet`1 goodfiles)
   at Mono.Documentation.MDocUpdater.DoUpdateAssemblies(String source, String dest)
   at Mono.Documentation.MDocUpdater.Run(IEnumerable`1 args)
   at Mono.Documentation.MDoc.Run(String[] args)
   at Mono.Documentation.MDoc.Main(String[] args)
See `mdoc help' for more information or use --debug to diagnose.
```

With release `5.0.0.2`. This is caused by `System.Windows.Presentation.dll`

**Comment by joelmartinez** [comment]
@dend hmm, I'm unable to reproduce this one :( 

This might seem an obvious thing, but I just want to double double check ... can you do `mdoc --version` with the executable you're using for this?

**Comment by joelmartinez** [comment]
_ok, apologies for the spam ... I wrote, essentially this comment, then deleted it cause I thought I had done something wrong, but no my original result was correct._

I was unable to reproduce this issue, unfortunately. Both running it from source, and also downloading the released package :( I get the following output:

```bash
$ mono mdoc.exe update "/Users/jmartinez/Downloads/netxip/.NET Framework 4.5/System.Windows.Presentation.dll" -o /tmp/presentationxml
New Type: System.AddIn.Pipeline.FrameworkElementAdapters
Member Added: public static System.AddIn.Contract.INativeHandleContract ViewToContractAdapter (System.Windows.FrameworkElement root);
Member Added: public static System.Windows.FrameworkElement ContractToViewAdapter (System.AddIn.Contract.INativeHandleContract nativeHandleContract);
Namespace Directory Created: System.AddIn.Pipeline
New Namespace File: System.AddIn.Pipeline
New Type: System.Windows.Threading.DispatcherExtensions
Member Added: public static System.Windows.Threading.DispatcherOperation BeginInvoke (this System.Windows.Threading.Dispatcher dispatcher, Action action);
Member Added: public static System.Windows.Threading.DispatcherOperation BeginInvoke (this System.Windows.Threading.Dispatcher dispatcher, Action action, System.Windows.Threading.DispatcherPriority priority);
Member Added: public static void Invoke (this System.Windows.Threading.Dispatcher dispatcher, Action action);
Member Added: public static void Invoke (this System.Windows.Threading.Dispatcher dispatcher, Action action, System.Windows.Threading.DispatcherPriority priority);
Member Added: public static void Invoke (this System.Windows.Threading.Dispatcher dispatcher, Action action, TimeSpan timeout);
Member Added: public static void Invoke (this System.Windows.Threading.Dispatcher dispatcher, Action action, TimeSpan timeout, System.Windows.Threading.DispatcherPriority priority);
Namespace Directory Created: System.Windows.Threading
New Namespace File: System.Windows.Threading
New Type: System.Windows.Threading.TaskExtensions
Member Added: public static bool IsDispatcherOperationTask (this System.Threading.Tasks.Task this);
Member Added: public static System.Windows.Threading.DispatcherOperationStatus DispatcherOperationWait (this System.Threading.Tasks.Task this);
Member Added: public static System.Windows.Threading.DispatcherOperationStatus DispatcherOperationWait (this System.Threading.Tasks.Task this, TimeSpan timeout);
Members Added: 11, Members Deleted: 0
Joels-MacBook-Pro:preview-mdoc-5.0.0.2 jmartinez$ 
```

Only because I want to rule out any oddness, can you double check the `--version` command on the executable that you're using, and make sure that it outputs `mdoc 5.0.0.2` ?

**Comment by joelmartinez** [comment]
This issue is in fact resolved, I confused it in discussions with #27 ... so am going to close it again

**Comment by dend** [comment]
Looks like this is still the case:

```
New Type: System.Linq.ParallelEnumerable
Member Added: public static System.Linq.ParallelQuery<TSource> AsParallel<TSource> (this System.Collections.Generic.IEnumerable<TSource> source);
mdoc: System.ArgumentNullException: Value cannot be null.
Parameter name: member
   at Mono.Documentation.MemberFormatter.GetDeclaration(IMemberDefinition member)
   at Mono.Documentation.MemberFormatter.GetDeclaration(MemberReference mreference)
   at Mono.Documentation.MDocUpdater.AddTargets(XmlNode member, DocsNodeInfo info)
   at Mono.Documentation.MDocUpdater.UpdateExtensionMethods(XmlElement e, DocsNodeInfo info)
   at Mono.Documentation.MDocUpdater.UpdateMember(DocsNodeInfo info, FrameworkTypeEntry typeEntry)
   at Mono.Documentation.MDocUpdater.MakeMember(XmlDocument doc, DocsNodeInfo info, FrameworkTypeEntry typeEntry)
   at Mono.Documentation.MDocUpdater.DoUpdateType2(String message, XmlDocument basefile, TypeDefinition type, FrameworkTypeEntry typeEntry, String output, Boolean insertSince)
   at Mono.Documentation.MDocUpdater.StubType(TypeDefinition type, String output)
   at Mono.Documentation.MDocUpdater.DoUpdateType(TypeDefinition type, FrameworkTypeEntry typeEntry, String basepath, String dest)
   at Mono.Documentation.MDocUpdater.DoUpdateAssembly(AssemblyDefinition assembly, XmlElement index_types, String source, String dest, HashSet`1 goodfiles)
   at Mono.Documentation.MDocUpdater.DoUpdateAssemblies(String source, String dest)
   at Mono.Documentation.MDocUpdater.Run(IEnumerable`1 args)
   at Mono.Documentation.MDoc.Run(String[] args)
   at Mono.Documentation.MDoc.Main(String[] args)
See `mdoc help' for more information or use --debug to diagnose.
```

@joelmartinez I run into this in `--frameworks` mode, when I run the `mdoc` tool across .NET Framework 2.0, 3.0, 3.5, 4.0.

**Comment by joelmartinez** [comment]
You can find this fix in https://github.com/mono/api-doc-tools/releases/tag/preview-5.0.0.4
