### ISSUE TITLE
[mdoc] Error when running on a folder with some assemblies being non-managed

### ISSUE THREAD

**Issue by dend** [mono/api-doc-tools#7]
For example, if you run:

```
mdoc update *.dll -o folder_name
```
And within the folder (current context) there are DLLs that are native, the tool will fail with:

```
Format of the executable (.exe) or library (.dll) is invalid
```

**Comment by joelmartinez** [comment]
In other cases, a user might receive an error as such while reading assemblies ... as the issue is with loading assemblies I'll attach the message to this GH issue until we find that it's an unrelated issue.

```
mdoc: System.ArgumentException: Value does not fall within the expected range.
   at Mono.Cecil.AssemblyDefinition.ReadAssembly(ModuleDefinition module)
   at Mono.Documentation.MDocUpdater.LoadAssembly(String name)
   at Mono.Documentation.MDocUpdater.<Run>c__AnonStorey2.<>m__E(String a)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Mono.Documentation.MDocUpdater.Run(IEnumerable`1 args)
   at Mono.Documentation.MDoc.Run(String[] args)
   at Mono.Documentation.MDoc.Main(String[] args)
See `mdoc help' for more information or use --debug to diagnose.
```
