### ISSUE TITLE
[mdoc] Vague error message with invalid entry in `frameworks.xml`

### ISSUE THREAD

**Issue by dend** [mono/api-doc-tools#79]
Getting the following when trying to reflect the library:

```
Updating: Microsoft.Data.Sqlite.SqliteParameterCollection
Updating: Microsoft.Data.Sqlite.SqliteTransaction
Updating: Microsoft.Data.Sqlite.SqliteType
Updating: Microsoft.Data.Sqlite.Internal.SqliteEngine
mdoc: System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Mono.Documentation.MDocUpdater.DoUpdateAssemblies(String source, String dest)
   at Mono.Documentation.MDocUpdater.Run(IEnumerable`1 args)
   at Mono.Documentation.MDoc.Run(String[] args)
   at Mono.Documentation.MDoc.Main(String[] args)
```

See attached the framework-ready DLLs.
[sqlite-test.zip](https://github.com/mono/api-doc-tools/files/967346/sqlite-test.zip)

**Comment by dend** [comment]
Disregard, there is a bad entry in `frameworks.xml`

**Comment by joelmartinez** [comment]
Well, I'd like to improve the error message here ...
